apiVersion: v2
description: A Helm chart cert-manager ACME Webhook for INWX
name: cert-manager-webhook-inwx
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
version: 0.6.0
appVersion: "0.6.0"
maintainers:
  - name: Stephan Müller
    url: https://gitlab.com/smueller18/cert-manager-webhook-inwx
  - name: Jonathan Vogt
    url: https://github.com/bitte-ein-bit/cert-manager-webhook-inwx
